using DreamGenClone.Domain.ModelManager;

namespace DreamGenClone.Domain.RolePlay;

/// <summary>
/// The two prompt "styles" a scene-image prompt can be drafted in. A scene-image prompt is written
/// in the dialect the target checkpoint reads: Pony-family checkpoints (Pony V6 XL, Pony Realism)
/// read dense Pony tag prompts; every natural-language checkpoint (SDXL / Juggernaut / Big Lust,
/// FLUX, and API image models) reads a natural-language photography brief. The Studio exposes one
/// editable draft per style and picks the style by the selected image model's family at render time.
/// </summary>
public enum SceneImagePromptStyle
{
    /// <summary>Not recorded (legacy rows generated by the default natural-language model path).</summary>
    Unknown = 0,

    /// <summary>Natural-language photography brief — used by SDXL-family, FLUX, and API image models.</summary>
    NaturalLanguage = 1,

    /// <summary>Dense Pony comma-separated tag prompt — used by Pony-family checkpoints (Pony V6, Pony Realism).</summary>
    PonyV6Tags = 2
}

/// <summary>
/// Maps an image model's resolved family/dialect to the prompt style the Studio tab uses, and
/// normalizes legacy <see cref="SceneImagePromptStyle.Unknown"/> records to the natural-language
/// style (the historical default model path was always a natural-language SDXL-family checkpoint).
/// </summary>
public static class SceneImagePromptStyleResolver
{
    public static SceneImagePromptStyle FromFamilyDialect(
        SceneImageModelFamily family,
        SceneImagePromptDialect dialect)
        => family == SceneImageModelFamily.Pony && dialect == SceneImagePromptDialect.PonyV6Tags
            ? SceneImagePromptStyle.PonyV6Tags
            : SceneImagePromptStyle.NaturalLanguage;

    public static SceneImagePromptStyle FromFamily(SceneImageModelFamily family)
        => family == SceneImageModelFamily.Pony
            ? SceneImagePromptStyle.PonyV6Tags
            : SceneImagePromptStyle.NaturalLanguage;

    /// <summary>Normalizes an Unknown/legacy style to NaturalLanguage for bucketing/persistence decisions.</summary>
    public static SceneImagePromptStyle Effective(SceneImagePromptStyle style)
        => style == SceneImagePromptStyle.Unknown ? SceneImagePromptStyle.NaturalLanguage : style;

    public static string DisplayLabel(SceneImagePromptStyle style)
        => style switch
        {
            SceneImagePromptStyle.PonyV6Tags => "Pony (V6 tags)",
            SceneImagePromptStyle.NaturalLanguage => "SDXL / natural language",
            _ => "Natural language"
        };
}
