using DreamGenClone.Domain.RolePlay;

namespace DreamGenClone.Domain.RolePlay;

/// <summary>How a scene asset was produced.</summary>
public enum SceneAssetKind
{
    /// <summary>Text-to-image render by the configured image model (Juggernaut).</summary>
    PromptGenerated = 1,

    /// <summary>Directly uploaded by the user.</summary>
    Uploaded = 2,

    /// <summary>Source-image edit (Qwen) of another asset. The original is untouched.</summary>
    Edited = 3,

    /// <summary>The front (identity anchor) view of a generated profile pack.</summary>
    ProfilePackFront = 4,

    /// <summary>One of the four non-front views (3/4L, 3/4R, profL, profR) of a generated profile pack.</summary>
    ProfilePackFace = 5
}

/// <summary>Async generation lifecycle for a scene asset.</summary>
public enum SceneAssetStatus
{
    /// <summary>Generation/editing job enqueued; model not yet called.</summary>
    Pending = 1,

    /// <summary>Bytes saved to disk; the asset is ready to view/download/reference.</summary>
    Complete = 2,

    /// <summary>Generation/editing failed; ErrorMessage holds the reason.</summary>
    Failed = 3
}

/// <summary>
/// A persisted, app-wide generated asset (prompt-generated, uploaded, or edited). Files live under
/// the git-ignored scene-image root and are served at <c>/scene-images/assets/...</c>. This is the
/// reusable asset library that character identity packs, locations, and wardrobe packs build on.
/// </summary>
public sealed class SceneAsset
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>User-settable display label.</summary>
    public string Name { get; set; } = string.Empty;

    public SceneAssetKind Kind { get; set; } = SceneAssetKind.PromptGenerated;

    public SceneAssetStatus Status { get; set; } = SceneAssetStatus.Pending;

    /// <summary>The generation or edit prompt that produced this asset (empty for uploads).</summary>
    public string Prompt { get; set; } = string.Empty;

    /// <summary>Parent asset when this is an edit revision.</summary>
    public string? SourceAssetId { get; set; }

    /// <summary>Snapshot of the resolved model used to produce this asset (informational).</summary>
    public string? ModelSnapshotJson { get; set; }

    public string? FileRelativePath { get; set; }

    public string MediaType { get; set; } = string.Empty;

    public int? Width { get; set; }
    public int? Height { get; set; }
    public long ByteLength { get; set; }

    /// <summary>Uppercase SHA-256 of the stored bytes.</summary>
    public string Sha256 { get; set; } = string.Empty;

    /// <summary>Face view when this asset is one view of a generated profile pack.</summary>
    public SceneImageReferenceFaceView? FaceView { get; set; }

    /// <summary>Identity pack this asset belongs to when generated by a profile pack run.</summary>
    public string? IdentityPackId { get; set; }

    /// <summary>Character the generated profile pack belongs to (characterProfileId).</summary>
    public string? CharacterProfileId { get; set; }

    public string? ErrorMessage { get; set; }

    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;
    public DateTime? StartedUtc { get; set; }
    public DateTime? CompletedUtc { get; set; }
    public DateTime UpdatedUtc { get; set; } = DateTime.UtcNow;
}
