#!/usr/bin/env python3
"""Generate a batch of near-frontal character face candidates via gpt-image-2
(TogetherAI), with the prompt hardened for CORRECT EYES (level, even, same size,
natural gaze).

Promoted from artifacts/tmp/dean-new-front/generate_front_v7.py (2026-09-02) —
the front-generation tool the character-profile-pack skill depends on. Dean's
proven eye-symmetry-hardened prompt is the built-in default; other characters are
generated by passing --name/--appearance (or a full --prompt override).

The TogetherAI API key is read from the Model Manager Providers row in the dev DB
(DPAPI / CurrentUser decrypted) unless TOGETHER_API_KEY is set.

Usage:
  python generate_front.py                                  # Dean default, 6 candidates
  python generate_front.py --count 12 --outdir <dir>
  python generate_front.py --name "Jane Doe" --appearance "long black hair, brown eyes" \\
      --count 8 --outdir <dir>
  python generate_front.py --prompt "<full custom prompt>" --count 4 --outdir <dir>

Outputs TRUE PNGs (gpt-image-2 returns JPEG bytes; re-encoded via Pillow) into
--outdir (default: artifacts/tmp/character-front-generator/<ts>/, git-ignored).
"""
import argparse
import base64
import ctypes
import ctypes.wintypes
import datetime
import io
import json
import os
import sqlite3
import sys
import time
import urllib.error
import urllib.request

from PIL import Image as PILImage

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
DEV_DB = os.path.join(REPO_ROOT, "DreamGenClone.Web", "data", "dreamgenclone.dev.db")

# Model Manager Providers row holding the encrypted TogetherAI key.
DEFAULT_TOGETHER_PROVIDER_ID = "f4c194b0-a139-4a34-ae8f-ab32b5a64885"
DEFAULT_API_URL = "https://api.together.xyz/v1/images/generations"
DEFAULT_MODEL = "openai/gpt-image-2"

# Proven eye-symmetry-hardened prompt (Dean v7 rebuild, 2026-09-02).
# gpt-image-2 has a systematic left-eye-lower bias — expect most of a batch to fail;
# generate batches until a candidate is ~0 on every axis (Dean needed 11; front_7 was -0.01%).
DEAN_PROMPT = (
    "Photorealistic head-and-shoulders portrait of Dean Winchester from Supernatural, season 18, "
    "showing his full head and hair. PERFECTLY frontal view: face perfectly centered and symmetric, "
    "head completely level with no tilt, both shoulders square and even. Eyes: perfectly level with "
    "each other on one horizontal line, identical in size and shape, evenly spaced, both fully open "
    "and looking straight at the camera with a natural level gaze, green eyes, natural catchlight, "
    "no squint, no asymmetry. Neutral relaxed expression, mouth closed, short light-brown hair, "
    "light stubble, strong jaw. Soft even studio lighting with no shadows across the face, plain "
    "light-gray background. Tack-sharp focus on the face, natural skin texture, fine hair detail, "
    "85mm, shallow depth of field, high detail."
)

# Generic near-frontal template for other characters. {name} and {appearance} are substituted.
GENERIC_TEMPLATE = (
    "Photorealistic head-and-shoulders portrait of {name}, showing the full head and hair. "
    "PERFECTLY frontal view: face perfectly centered and symmetric, head completely level with "
    "no tilt, both shoulders square and even. Eyes: perfectly level with each other on one "
    "horizontal line, identical in size and shape, evenly spaced, both fully open and looking "
    "straight at the camera with a natural level gaze, natural catchlight, no squint, no "
    "asymmetry. {appearance}. Neutral relaxed expression, mouth closed. Soft even studio "
    "lighting with no shadows across the face, plain light-gray background. Tack-sharp focus "
    "on the face, natural skin texture, fine hair detail, 85mm, shallow depth of field, "
    "high detail."
)

# No-garment variant (2026-09-10). DEAN_PROMPT is used VERBATIM; the ONLY addition constrains the
# FRAMING. Do NOT describe his features - the model already knows who Dean is.
#
# WHY FRAMING AND NOT "no clothing": the v7 reference itself shows a navy/black jacket over a blue
# collared shirt, and identity conditioning pulls that garment into every render - ANY clothing in
# the reference leaks. So the reference must contain no garment at all.
# BUT the literal wording "He is wearing no clothing at all: no shirt, no collar..." is REJECTED by
# the OpenAI safety system (HTTP 400, "Your request was rejected by the safety system"). Four
# framings were probed against moderation (artifacts/tmp/dean-new-front/probe_variants.py); only
# this one both PASSED moderation and produced a frame with no clothing at all:
#   crop at base of neck  -> pass + NO clothing visible   <-- used here
#   passport-style crop   -> pass + dark crew-neck shirt at the bottom edge
#   ends just below jaw   -> pass + dark blue collared shirt visible
#   "plain light-gray crew-neck top" -> pass + a heather gray t-shirt (garment present)
# Do not reintroduce "no clothing"/"shirtless" wording; it 400s.
_NO_GARMENT_FRAMING = (
    " The image is a tight headshot cropped at the base of the neck, so only his head, hair and "
    "neck are in frame."
)

# v7 sentence order preserved exactly; the clause is inserted after the subject sentence rather
# than appended, because a trailing tail is weakly weighted by image models.
DEAN_NO_GARMENT_PROMPT = DEAN_PROMPT.replace(
    "showing his full head and hair. ",
    "showing his full head and hair." + _NO_GARMENT_FRAMING + " ",
)
assert DEAN_NO_GARMENT_PROMPT != DEAN_PROMPT, "no-garment framing clause was not inserted"

# Built-in character prompts (key = --character value). Add new characters here.
CHARACTER_PROMPTS = {
    "dean": DEAN_PROMPT,
    "dean-no-garment": DEAN_NO_GARMENT_PROMPT,
}


def resolve_dev_db() -> str:
    """Walk up from this file until the live dev DB is found."""
    cur = os.path.dirname(os.path.abspath(__file__))
    while True:
        candidate = os.path.join(cur, "DreamGenClone.Web", "data", "dreamgenclone.dev.db")
        if os.path.exists(candidate):
            return candidate
        parent = os.path.dirname(cur)
        if parent == cur:
            break
        cur = parent
    raise RuntimeError(
        "Could not locate DreamGenClone.Web/data/dreamgenclone.dev.db; "
        "pass --db or set DB explicitly.")


def dpapi_unprotect(blob: bytes) -> bytes:
    class DATA_BLOB(ctypes.Structure):
        _fields_ = [("cbData", ctypes.wintypes.DWORD), ("pbData", ctypes.POINTER(ctypes.c_char))]

    buf_in = ctypes.create_string_buffer(blob, len(blob))
    in_blob = DATA_BLOB(len(blob), ctypes.cast(buf_in, ctypes.POINTER(ctypes.c_char)))
    out_blob = DATA_BLOB()
    if not ctypes.windll.crypt32.CryptUnprotectData(
            ctypes.byref(in_blob), None, None, None, None, 0, ctypes.byref(out_blob)):
        raise ctypes.WinError()
    try:
        return ctypes.string_at(out_blob.pbData, out_blob.cbData)
    finally:
        ctypes.windll.kernel32.LocalFree(out_blob.pbData)


def get_together_key(provider_id: str, db_path: str) -> str:
    conn = sqlite3.connect(db_path)
    try:
        row = conn.execute(
            "SELECT ApiKeyEncrypted FROM Providers WHERE Id = ?", (provider_id,)).fetchone()
    finally:
        conn.close()
    if not row or not row[0]:
        raise RuntimeError("Together provider key not found in DB")
    return dpapi_unprotect(base64.b64decode(row[0])).decode("utf-8")


def call_gpt_image(key: str, prompt: str, model: str, api_url: str,
                   attempts: int = 4) -> bytes:
    """POST one generation, retrying TRANSIENT failures.

    gpt-image-2 moderation on this prompt is nondeterministic: the SAME prompt returns HTTP 400
    "rejected by the safety system" on one call and 200 on the next (observed 2026-09-10). Without
    a retry a single blip aborts the whole batch, so 400/429/5xx are retried with backoff.
    """
    body = json.dumps({
        "model": model,
        "prompt": prompt,
        "n": 1,
        "width": 1024,
        "height": 1024,
        "response_format": "b64_json",
    }).encode("utf-8")

    last_err: Exception | None = None
    for attempt in range(1, attempts + 1):
        req = urllib.request.Request(api_url, data=body, method="POST")
        req.add_header("Authorization", f"Bearer {key}")
        req.add_header("Content-Type", "application/json")
        req.add_header("User-Agent",
                       "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
            data = payload.get("data") or []
            if not data or not data[0].get("b64_json"):
                raise RuntimeError(f"No image data in response: {str(payload)[:400]}")
            return base64.b64decode(data[0]["b64_json"])
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", "replace")[:300].replace("\n", " ")
            last_err = urllib.error.HTTPError(e.url, e.code, f"{e.reason} | {detail}", e.hdrs, None)
            retryable = e.code in (400, 408, 409, 429) or e.code >= 500
            if not retryable or attempt == attempts:
                raise last_err from None
            delay = 2 ** attempt
            print(f"    HTTP {e.code} (attempt {attempt}/{attempts}); retrying in {delay}s ...",
                  flush=True)
            time.sleep(delay)
    raise last_err if last_err else RuntimeError("generation failed")


def build_prompt(name: str, appearance: str, character: str, override: str | None) -> str:
    if override:
        return override
    if character:
        key = character.strip().lower()
        if key in CHARACTER_PROMPTS:
            return CHARACTER_PROMPTS[key]
        raise RuntimeError(
            f"Unknown --character '{character}'. Built-ins: {sorted(CHARACTER_PROMPTS)}. "
            "Use --name/--appearance or --prompt for a custom character.")
    appearance = appearance.strip() if appearance else "natural eye color"
    return GENERIC_TEMPLATE.format(name=name.strip(), appearance=appearance)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate near-frontal character face candidates (gpt-image-2).")
    ap.add_argument("--count", type=int, default=6, help="Number of candidates to generate (default 6).")
    ap.add_argument("--outdir", default=None, help="Output dir for TRUE PNGs (default artifacts/tmp/character-front-generator/<ts>).")
    ap.add_argument("--character", default=None, help="Built-in character prompt key, e.g. 'dean'.")
    ap.add_argument("--name", default=None, help="Character name for the generic near-frontal template.")
    ap.add_argument("--appearance", default=None, help="Appearance clause (hair/eyes/etc.) for the generic template.")
    ap.add_argument("--prompt", default=None, help="Full prompt override (bypasses template/registry).")
    ap.add_argument("--model", default=DEFAULT_MODEL, help=f"Image model (default {DEFAULT_MODEL}).")
    ap.add_argument("--api-url", default=DEFAULT_API_URL, help="Image generations API URL.")
    ap.add_argument("--provider-id", default=DEFAULT_TOGETHER_PROVIDER_ID, help="Model Manager Providers row Id for the key.")
    ap.add_argument("--db", default=None, help="Path to the dev DB (auto-detected if omitted).")
    args = ap.parse_args(argv)

    if args.count < 1:
        raise SystemExit("--count must be >= 1")
    if not (args.prompt or args.character or args.name):
        # Default to the proven Dean prompt when nothing character-specific is given.
        args.character = "dean"

    prompt = build_prompt(args.name or "character", args.appearance or "", args.character, args.prompt)
    db_path = args.db or resolve_dev_db()
    out_dir = os.path.abspath(args.outdir or os.path.join(
        REPO_ROOT, "artifacts", "tmp", "character-front-generator",
        datetime.datetime.now().strftime("%Y%m%d-%H%M%S")))
    os.makedirs(out_dir, exist_ok=True)

    key = os.environ.get("TOGETHER_API_KEY") or get_together_key(args.provider_id, db_path)

    print(f"Model: {args.model}  Size: 1024x1024  Candidates: {args.count}  Out: {out_dir}")
    print("Prompt:")
    print(prompt)
    print("---")
    failed: list[int] = []
    for i in range(1, args.count + 1):
        path = os.path.join(out_dir, f"front_{i}.png")
        if os.path.exists(path):
            print(f"[{i}/{args.count}] exists, skipping {path}")
            continue
        print(f"[{i}/{args.count}] generating ...", flush=True)
        try:
            img_bytes = call_gpt_image(key, prompt, args.model, args.api_url)
        except Exception as e:  # noqa: BLE001 - keep the batch going, report at the end
            failed.append(i)
            print(f"  FAILED: {e}", flush=True)
            continue
        im = PILImage.open(io.BytesIO(img_bytes))
        im.load()
        if im.mode != "RGB":
            im = im.convert("RGB")
        im.save(path, "PNG")
        print(f"  saved {path} ({os.path.getsize(path)} bytes, "
              f"{im.size[0]}x{im.size[1]} true PNG)", flush=True)
    if failed:
        print(f"INCOMPLETE - {len(failed)} candidate(s) failed: {failed}. "
              "Re-run the same command to fill the gaps (existing files are skipped).")
    print("DONE")
    return 0 if not failed else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
