using System.Text.Json;
using DreamGenClone.Application.RolePlay;
using DreamGenClone.Application.StoryAnalysis;
using DreamGenClone.Application.Templates;
using DreamGenClone.Domain.RolePlay;
using DreamGenClone.Domain.StoryAnalysis;
using DreamGenClone.Domain.Templates;
using Microsoft.Extensions.Logging;

namespace DreamGenClone.Infrastructure.RolePlay;

public sealed class ScenarioGuidanceGenerator : IScenarioGuidanceGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly ITemplateService _templateService;
    private readonly IStatWillingnessProfileService? _statWillingnessProfileService;
    private readonly IHusbandAwarenessProfileService? _husbandAwarenessProfileService;
    private readonly IScenarioEngineSettingsRepository? _engineSettingsRepository;
    private readonly ILogger<ScenarioGuidanceGenerator> _logger;

    public ScenarioGuidanceGenerator(
        ITemplateService templateService,
        ILogger<ScenarioGuidanceGenerator> logger,
        IStatWillingnessProfileService? statWillingnessProfileService = null,
        IHusbandAwarenessProfileService? husbandAwarenessProfileService = null,
        IScenarioEngineSettingsRepository? engineSettingsRepository = null)
    {
        _templateService = templateService;
        _logger = logger;
        _statWillingnessProfileService = statWillingnessProfileService;
        _husbandAwarenessProfileService = husbandAwarenessProfileService;
        _engineSettingsRepository = engineSettingsRepository;
    }

    public async Task<ScenarioGuidanceOutput> GenerateGuidanceAsync(
        ScenarioGuidanceRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var characterBehavioralFrames = new Dictionary<string, string>();
        // Note B-042: behavioral frames are generated by IBehavioralFrameGenerator in ScenarioGuidanceContextFactory (T016);

        var template = await ResolveTemplateAsync(request, cancellationToken);
        var settings = await LoadSettingsOrDefaultAsync(cancellationToken);
        if (template is null)
        {
            var fallbackText = BuildFallbackGuidance(request.CurrentPhase, request.ActiveScenarioId);

            var fallbackWillingness = await BuildWillingnessInterpretationAsync(request, settings, cancellationToken);
            if (!string.IsNullOrWhiteSpace(fallbackWillingness))
            {
                fallbackText = $"{fallbackText} {fallbackWillingness}";
            }

            var fallbackResistance = await BuildResistanceInterpretationAsync(request, settings, cancellationToken);
            if (!string.IsNullOrWhiteSpace(fallbackResistance))
            {
                fallbackText = $"{fallbackText} {fallbackResistance}";
            }

            return new ScenarioGuidanceOutput
            {
                GuidanceText = fallbackText,
                CharacterBehavioralFrames = characterBehavioralFrames,
                Source = "Fallback"
            };
        }

        var phaseGuidance = ResolvePhaseGuidance(template, request.CurrentPhase);
        var statInterpretation = BuildStatInterpretation(
            request.AverageDesire,
            request.AverageRestraint,
            request.AverageDominance,
            request.AverageLoyalty);
        var guidanceText = string.IsNullOrWhiteSpace(statInterpretation)
            ? phaseGuidance
            : $"{phaseGuidance} {statInterpretation}";

        var willingnessInterpretation = await BuildWillingnessInterpretationAsync(request, settings, cancellationToken);
        if (!string.IsNullOrWhiteSpace(willingnessInterpretation))
        {
            guidanceText = $"{guidanceText} {willingnessInterpretation}";
        }

        var resistanceInterpretation = await BuildResistanceInterpretationAsync(request, settings, cancellationToken);
        if (!string.IsNullOrWhiteSpace(resistanceInterpretation))
        {
            guidanceText = $"{guidanceText} {resistanceInterpretation}";
        }

        return new ScenarioGuidanceOutput
        {
            GuidanceText = guidanceText,
            CharacterBehavioralFrames = characterBehavioralFrames,
            EmphasisPoints = template.EmphasisPoints,
            AvoidancePoints = template.AvoidancePoints,
            Source = $"Template:{template.ScenarioId}"
        };
    }

    private async Task<ScenarioEngineSettings> LoadSettingsOrDefaultAsync(CancellationToken cancellationToken)
    {
        if (_engineSettingsRepository is null)
        {
            return new ScenarioEngineSettings();
        }

        try
        {
            return await _engineSettingsRepository.LoadAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "ScenarioGuidanceGenerator: could not load engine settings; using defaults for willingness score.");
            return new ScenarioEngineSettings();
        }
    }

    private async Task<ScenarioGuidanceTemplate?> ResolveTemplateAsync(
        ScenarioGuidanceRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.ActiveScenarioId))
        {
            return null;
        }

        var templates = await _templateService.GetAllAsync(TemplateType.ScenarioGuidance, cancellationToken);
        if (templates.Count == 0)
        {
            return null;
        }

        foreach (var template in templates)
        {
            try
            {
                var payload = JsonSerializer.Deserialize<ScenarioGuidanceTemplate>(template.Content, JsonOptions);
                if (payload is null)
                {
                    continue;
                }

                if (!string.Equals(payload.ScenarioId, request.ActiveScenarioId, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (!string.IsNullOrWhiteSpace(request.VariantId)
                    && !string.IsNullOrWhiteSpace(payload.VariantId)
                    && !string.Equals(payload.VariantId, request.VariantId, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                return payload;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse scenario guidance template {TemplateId}", template.Id);
            }
        }

        return null;
    }

    private static string ResolvePhaseGuidance(ScenarioGuidanceTemplate template, string currentPhase)
    {
        if (template.PhaseGuidance.TryGetValue(currentPhase, out var direct) && !string.IsNullOrWhiteSpace(direct))
        {
            return direct;
        }

        if (template.PhaseGuidance.TryGetValue("Default", out var fallback) && !string.IsNullOrWhiteSpace(fallback))
        {
            return fallback;
        }

        return BuildFallbackGuidance(currentPhase, template.ScenarioId);
    }

    private static string BuildStatInterpretation(
        double averageDesire,
        double averageRestraint,
        double averageDominance,
        double averageLoyalty)
    {
        var notes = new List<string>();

        if (averageDesire >= 70)
        {
            notes.Add("High desire suggests proactive pursuit by involved characters.");
        }
        else if (averageDesire <= 35)
        {
            notes.Add("Lower desire suggests slower pacing and stronger motivational setup.");
        }

        if (averageRestraint >= 70)
        {
            notes.Add("High restraint implies composed behavior and guarded choices.");
        }
        else if (averageRestraint <= 35)
        {
            notes.Add("Low restraint supports impulse-driven escalation.");
        }

        var agencyScore = averageDominance - averageRestraint + (averageDesire / 3.0);
        if (agencyScore >= 60)
        {
            notes.Add("Agency profile is proactive: the actor can initiate and direct escalation.");
        }
        else if (agencyScore >= 30)
        {
            notes.Add("Agency profile is opportunistic: the actor responds readily to invitation and momentum.");
        }
        else
        {
            notes.Add("Agency profile is reactive: stronger external invitation is needed before escalation.");
        }

        var cheatingPressure = averageLoyalty - (averageDesire / 2.0) + (averageRestraint / 2.0);
        if (cheatingPressure >= 80)
        {
            notes.Add("Loyalty pressure is high, so keep decisions spouse-anchored and avoid infidelity pivots.");
        }
        else if (cheatingPressure >= 60)
        {
            notes.Add("Loyalty pressure is moderate-high; require stronger trust and setup before boundary-crossing choices.");
        }
        else if (cheatingPressure >= 40)
        {
            notes.Add("Loyalty pressure is mixed; use ambivalence and conditional decision framing.");
        }
        else
        {
            notes.Add("Loyalty pressure is low, so transgressive choices can emerge with less resistance.");
        }

        return string.Join(" ", notes);
    }

    private static string BuildFallbackGuidance(string phase, string? scenarioLabel)
    {
        var label = string.IsNullOrWhiteSpace(scenarioLabel) ? "current narrative direction" : scenarioLabel;

        return phase switch
        {
            "BuildUp" => "Use subtle, exploratory cues and avoid hard commitment language.",
            "Committed" => $"Keep narrative choices anchored to '{label}' and avoid introducing conflicting pivots.",
            "Approaching" => $"Increase anticipation and intensity while preserving coherence with '{label}'.",
            "Climax" => $"Deliver a high-intensity culmination explicitly framed around '{label}'.",
            "Reset" => "Transition to reflective tone and prepare for next build-up.",
            _ => "Maintain coherent narrative progression."
        };
    }

    private async Task<string> BuildWillingnessInterpretationAsync(ScenarioGuidanceRequest request, ScenarioEngineSettings settings, CancellationToken cancellationToken)
    {
        // B-034: the willingness/ceiling block only applies when a Wife is present.
        if (FindRole(request.CharacterRuntimeStats, "Wife") is null)
        {
            return string.Empty;
        }

        if (_statWillingnessProfileService is null || string.IsNullOrWhiteSpace(request.SelectedWillingnessProfileId))
        {
            return string.Empty;
        }

        var profile = await _statWillingnessProfileService.GetAsync(request.SelectedWillingnessProfileId, cancellationToken);
        if (profile is null || profile.Thresholds.Count == 0)
        {
            return string.Empty;
        }

        // B-034: resolve the Wife's explicitness ceiling from min(Desire, willingness) —
        // the ceiling is bounded by Desire so a low-Desire Wife stays low-explicitness
        // even when her willingness score is high.
        var inputs = ResolveWillingnessInputs(request);
        var willingness = ComputeWillingnessScore(inputs, settings);
        var ceiling = WifeWillingnessCalculator.ComputeCeiling(willingness, inputs.Desire);

        var threshold = profile.Thresholds
            .OrderBy(x => x.SortOrder)
            .ThenBy(x => x.MinValue)
            .FirstOrDefault(x => ceiling >= x.MinValue && ceiling <= x.MaxValue);

        if (threshold is null)
        {
            return string.Empty;
        }

        var examples = threshold.ExampleScenarios.Count == 0
            ? string.Empty
            : $" (Examples: {string.Join(", ", threshold.ExampleScenarios)})";

        // B-034: escalation ladder — all bands from the bottom up to (and including) the
        // ceiling band, so the model knows she is capable of escalating through every level
        // up to the cap (it may move up the ladder within a scene, but never past the ceiling).
        var ladder = profile.Thresholds
            .Where(x => x.SortOrder <= threshold.SortOrder)
            .OrderBy(x => x.SortOrder)
            .ThenBy(x => x.MinValue)
            .Select(x => x.ExplicitnessLevel)
            .ToList();

        // Contract (willingness-prompt-contract.md §3.3): the block is
        //   Verdict: {Verdict} — {directive}
        //   Ceiling: {ExplicitnessLevel} — {PromptGuideline} (Examples: ...)
        //   Ladder: {b1}, {b2}, …, {ceiling band}
        //   Details: Willingness to Cheat = {willingness} (Desire=…, Loyalty=…, …); Ceiling = min(Desire, willingness) = {ceiling}.
        // This method supplies the Ceiling, Ladder and Details lines; the Verdict line comes
        // from BuildResistanceInterpretationAsync.
        var ceilingLine = $"Ceiling: {threshold.ExplicitnessLevel} — {threshold.PromptGuideline}{examples}";

        var ladderLine = ladder.Count == 0
            ? string.Empty
            : $"Ladder: {string.Join(", ", ladder)}";

        var detailsLine = "Details: Willingness to Cheat = "
            + $"{willingness} (Desire={inputs.Desire}, Loyalty={inputs.Loyalty}, "
            + $"SeductionReceptivity={inputs.SeductionReceptivity}, BoundaryFirmness={inputs.BoundaryFirmness}, "
            + $"Attentiveness={inputs.Attentiveness}, IntimacyAvailability={inputs.IntimacyAvailability}); "
            + $"Ceiling = min(Desire, willingness) = {ceiling}.";

        return ladderLine.Length == 0
            ? $"{ceilingLine} {detailsLine}"
            : $"{ceilingLine} {ladderLine} {detailsLine}";
    }

    private async Task<string> BuildResistanceInterpretationAsync(ScenarioGuidanceRequest request, ScenarioEngineSettings settings, CancellationToken cancellationToken)
    {
        // B-034: the verdict block only applies when a Wife is present.
        if (FindRole(request.CharacterRuntimeStats, "Wife") is null)
        {
            return string.Empty;
        }

        // B-034: verdict comes from the unified willingness score via verdict bands (config on
        // ScenarioEngineSettings). The StatResistanceProfiles catalog is retired for the verdict
        // (plan tasks.md decision #3); its loyalty-keyed bands inverted the meaning when fed the
        // willingness score. Directive text is UI-backed config (repo rule), not hardcoded.
        var inputs = ResolveWillingnessInputs(request);
        var willingness = ComputeWillingnessScore(inputs, settings);
        var verdict = ResolveVerdictLabel(settings, willingness);
        var directive = ResolveVerdictDirective(settings, verdict);

        return $"Verdict: {verdict} — {directive}";
    }

    /// <summary>
    /// B-034: the Wife/Husband stat inputs feeding the Option A willingness score, resolved from
    /// the session snapshots. Missing inputs default to 50 (neutral).
    /// </summary>
    private WillingnessInputs ResolveWillingnessInputs(ScenarioGuidanceRequest request)
    {
        var snapshots = request.CharacterRuntimeStats;
        var wife = FindRole(snapshots, "Wife");
        var husband = FindRole(snapshots, "Husband");
        var (desire, loyalty) = ResolveWifeDesireLoyalty(request, snapshots);

        return new WillingnessInputs(
            desire,
            loyalty,
            GetEncounterStatOrDefault(wife, "SeductionReceptivity"),
            GetEncounterStatOrDefault(wife, "BoundaryFirmness"),
            GetEncounterStatOrDefault(husband, "Attentiveness"),
            GetEncounterStatOrDefault(husband, "IntimacyAvailability"));
    }

    private int ComputeWillingnessScore(WillingnessInputs inputs, ScenarioEngineSettings settings)
        => WifeWillingnessCalculator.ComputeWillingnessToCheat(
            inputs.Desire,
            inputs.Loyalty,
            inputs.SeductionReceptivity,
            inputs.BoundaryFirmness,
            inputs.Attentiveness,
            inputs.IntimacyAvailability,
            settings.WillingnessDesireLoyaltyWeight,
            settings.WillingnessBehaviorWeight,
            settings.WillingnessMaritalDeficitWeight);

    private string ResolveVerdictDirective(ScenarioEngineSettings settings, string verdict)
        => verdict switch
        {
            "NO" => settings.WillingnessVerdictNoDirective,
            "MAYBE" => settings.WillingnessVerdictMaybeDirective,
            _ => settings.WillingnessVerdictYesDirective
        };

    private string ResolveVerdictLabel(ScenarioEngineSettings settings, int willingness)
        => WifeWillingnessCalculator.ResolveVerdict(
            willingness,
            settings.WillingnessVerdictNoMax,
            settings.WillingnessVerdictMaybeMax);

    private static CharacterStatProfileV2? FindRole(
        IReadOnlyDictionary<string, CharacterStatProfileV2>? snapshots,
        string role)
    {
        if (snapshots is null) return null;
        return snapshots.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, role, StringComparison.OrdinalIgnoreCase));
    }

    private static int GetEncounterStatOrDefault(CharacterStatProfileV2? profile, string key)
    {
        if (profile?.RuntimeEncounterStats is null) return 50;
        return profile.RuntimeEncounterStats.TryGetValue(key, out var val) ? val : 50;
    }

    private static (int Desire, int Loyalty) ResolveWifeDesireLoyalty(
        ScenarioGuidanceRequest request,
        IReadOnlyDictionary<string, CharacterStatProfileV2>? snapshots)
    {
        var wife = FindRole(snapshots, "Wife");
        return (
            wife?.Desire ?? (int)Math.Round(request.AverageDesire, MidpointRounding.AwayFromZero),
            wife?.Loyalty ?? (int)Math.Round(request.AverageLoyalty, MidpointRounding.AwayFromZero));
    }

    private int ComputeMotivationScore(ScenarioGuidanceRequest request)
    {
        // Resolve per-character RuntimeEncounterStat values.
        // Default to 50 (neutral) when a character role or stat is not found.
        var stats = request.CharacterRuntimeStats;
        if (stats is null || stats.Count == 0)
        {
            return 0;
        }

        // Find characters by role
        var wifeStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "Wife", StringComparison.OrdinalIgnoreCase));
        var husbandStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "Husband", StringComparison.OrdinalIgnoreCase));
        var otherManStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "OtherMan", StringComparison.OrdinalIgnoreCase));

        // Resolve dimension values (default 50 = neutral)
        var attentiveness = husbandStats?.RuntimeEncounterStats?.TryGetValue("Attentiveness", out var att) == true
            ? att : 50;
        var intimacyAvailability = husbandStats?.RuntimeEncounterStats?.TryGetValue("IntimacyAvailability", out var ia) == true
            ? ia : 50;
        var selfRespect = wifeStats?.RuntimeEncounterStats?.TryGetValue("SelfRespect", out var sr) == true
            ? sr : 50;
        var persistencePastLimits = otherManStats?.RuntimeEncounterStats?.TryGetValue("PersistencePastLimits", out var ppl) == true
            ? ppl : 50;

        // Formula: ((100−Attentiveness) + (100−IntimacyAvailability) + (100−SelfRespect) + PersistencePastLimits) / 4
        var score = ((100 - attentiveness) + (100 - intimacyAvailability) + (100 - selfRespect) + persistencePastLimits) / 4.0;
        return (int)Math.Round(score, MidpointRounding.AwayFromZero);
    }

    private static double ResolveAverageForStat(ScenarioGuidanceRequest request, string statName)
    {
        if (string.Equals(statName, "Desire", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageDesire;
        }

        if (string.Equals(statName, "Restraint", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageRestraint;
        }

        if (string.Equals(statName, "Tension", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageTension;
        }

        if (string.Equals(statName, "Connection", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageConnection;
        }

        if (string.Equals(statName, "Dominance", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageDominance;
        }

        if (string.Equals(statName, "Loyalty", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageLoyalty;
        }

        return request.AverageDesire;
    }
}

/// <summary>
/// B-034: the resolved Wife/Husband stat inputs feeding the Option A willingness score.
/// </summary>
internal readonly record struct WillingnessInputs(
    int Desire,
    int Loyalty,
    int SeductionReceptivity,
    int BoundaryFirmness,
    int Attentiveness,
    int IntimacyAvailability);
