using System.Text.Json;
using DreamGenClone.Application.RolePlay;
using DreamGenClone.Application.StoryAnalysis;
using DreamGenClone.Application.Templates;
using DreamGenClone.Domain.RolePlay;
using DreamGenClone.Domain.StoryAnalysis;
using DreamGenClone.Domain.Templates;
using Microsoft.Extensions.Logging;

namespace DreamGenClone.Infrastructure.RolePlay;

public sealed class ScenarioGuidanceGenerator : IScenarioGuidanceGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly ITemplateService _templateService;
    private readonly IStatWillingnessProfileService? _statWillingnessProfileService;
    private readonly IStatResistanceProfileService? _statResistanceProfileService;
    private readonly IHusbandAwarenessProfileService? _husbandAwarenessProfileService;
    private readonly ILogger<ScenarioGuidanceGenerator> _logger;

    public ScenarioGuidanceGenerator(
        ITemplateService templateService,
        ILogger<ScenarioGuidanceGenerator> logger,
        IStatWillingnessProfileService? statWillingnessProfileService = null,
        IStatResistanceProfileService? statResistanceProfileService = null,
        IHusbandAwarenessProfileService? husbandAwarenessProfileService = null)
    {
        _templateService = templateService;
        _logger = logger;
        _statWillingnessProfileService = statWillingnessProfileService;
        _statResistanceProfileService = statResistanceProfileService;
        _husbandAwarenessProfileService = husbandAwarenessProfileService;
    }

    public async Task<ScenarioGuidanceOutput> GenerateGuidanceAsync(
        ScenarioGuidanceRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var characterBehavioralFrames = new Dictionary<string, string>();
        // Note B-042: behavioral frames are generated by IBehavioralFrameGenerator in ScenarioGuidanceContextFactory (T016);

        var template = await ResolveTemplateAsync(request, cancellationToken);
        if (template is null)
        {
            return new ScenarioGuidanceOutput
            {
                GuidanceText = BuildFallbackGuidance(request.CurrentPhase, request.ActiveScenarioId),
                CharacterBehavioralFrames = characterBehavioralFrames,
                Source = "Fallback"
            };
        }

        var phaseGuidance = ResolvePhaseGuidance(template, request.CurrentPhase);
        var statInterpretation = BuildStatInterpretation(
            request.AverageDesire,
            request.AverageRestraint,
            request.AverageDominance,
            request.AverageLoyalty);
        var guidanceText = string.IsNullOrWhiteSpace(statInterpretation)
            ? phaseGuidance
            : $"{phaseGuidance} {statInterpretation}";

        var willingnessInterpretation = await BuildWillingnessInterpretationAsync(request, cancellationToken);
        if (!string.IsNullOrWhiteSpace(willingnessInterpretation))
        {
            guidanceText = $"{guidanceText} {willingnessInterpretation}";
        }

        var resistanceInterpretation = await BuildResistanceInterpretationAsync(request, cancellationToken);
        if (!string.IsNullOrWhiteSpace(resistanceInterpretation))
        {
            guidanceText = $"{guidanceText} {resistanceInterpretation}";
        }

        return new ScenarioGuidanceOutput
        {
            GuidanceText = guidanceText,
            CharacterBehavioralFrames = characterBehavioralFrames,
            EmphasisPoints = template.EmphasisPoints,
            AvoidancePoints = template.AvoidancePoints,
            Source = $"Template:{template.ScenarioId}"
        };
    }

    private async Task<ScenarioGuidanceTemplate?> ResolveTemplateAsync(
        ScenarioGuidanceRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.ActiveScenarioId))
        {
            return null;
        }

        var templates = await _templateService.GetAllAsync(TemplateType.ScenarioGuidance, cancellationToken);
        if (templates.Count == 0)
        {
            return null;
        }

        foreach (var template in templates)
        {
            try
            {
                var payload = JsonSerializer.Deserialize<ScenarioGuidanceTemplate>(template.Content, JsonOptions);
                if (payload is null)
                {
                    continue;
                }

                if (!string.Equals(payload.ScenarioId, request.ActiveScenarioId, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (!string.IsNullOrWhiteSpace(request.VariantId)
                    && !string.IsNullOrWhiteSpace(payload.VariantId)
                    && !string.Equals(payload.VariantId, request.VariantId, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                return payload;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse scenario guidance template {TemplateId}", template.Id);
            }
        }

        return null;
    }

    private static string ResolvePhaseGuidance(ScenarioGuidanceTemplate template, string currentPhase)
    {
        if (template.PhaseGuidance.TryGetValue(currentPhase, out var direct) && !string.IsNullOrWhiteSpace(direct))
        {
            return direct;
        }

        if (template.PhaseGuidance.TryGetValue("Default", out var fallback) && !string.IsNullOrWhiteSpace(fallback))
        {
            return fallback;
        }

        return BuildFallbackGuidance(currentPhase, template.ScenarioId);
    }

    private static string BuildStatInterpretation(
        double averageDesire,
        double averageRestraint,
        double averageDominance,
        double averageLoyalty)
    {
        var notes = new List<string>();

        if (averageDesire >= 70)
        {
            notes.Add("High desire suggests proactive pursuit by involved characters.");
        }
        else if (averageDesire <= 35)
        {
            notes.Add("Lower desire suggests slower pacing and stronger motivational setup.");
        }

        if (averageRestraint >= 70)
        {
            notes.Add("High restraint implies composed behavior and guarded choices.");
        }
        else if (averageRestraint <= 35)
        {
            notes.Add("Low restraint supports impulse-driven escalation.");
        }

        var agencyScore = averageDominance - averageRestraint + (averageDesire / 3.0);
        if (agencyScore >= 60)
        {
            notes.Add("Agency profile is proactive: the actor can initiate and direct escalation.");
        }
        else if (agencyScore >= 30)
        {
            notes.Add("Agency profile is opportunistic: the actor responds readily to invitation and momentum.");
        }
        else
        {
            notes.Add("Agency profile is reactive: stronger external invitation is needed before escalation.");
        }

        var cheatingPressure = averageLoyalty - (averageDesire / 2.0) + (averageRestraint / 2.0);
        if (cheatingPressure >= 80)
        {
            notes.Add("Loyalty pressure is high, so keep decisions spouse-anchored and avoid infidelity pivots.");
        }
        else if (cheatingPressure >= 60)
        {
            notes.Add("Loyalty pressure is moderate-high; require stronger trust and setup before boundary-crossing choices.");
        }
        else if (cheatingPressure >= 40)
        {
            notes.Add("Loyalty pressure is mixed; use ambivalence and conditional decision framing.");
        }
        else
        {
            notes.Add("Loyalty pressure is low, so transgressive choices can emerge with less resistance.");
        }

        return string.Join(" ", notes);
    }

    private static string BuildFallbackGuidance(string phase, string? scenarioLabel)
    {
        var label = string.IsNullOrWhiteSpace(scenarioLabel) ? "current narrative direction" : scenarioLabel;

        return phase switch
        {
            "BuildUp" => "Use subtle, exploratory cues and avoid hard commitment language.",
            "Committed" => $"Keep narrative choices anchored to '{label}' and avoid introducing conflicting pivots.",
            "Approaching" => $"Increase anticipation and intensity while preserving coherence with '{label}'.",
            "Climax" => $"Deliver a high-intensity culmination explicitly framed around '{label}'.",
            "Reset" => "Transition to reflective tone and prepare for next build-up.",
            _ => "Maintain coherent narrative progression."
        };
    }

    private async Task<string> BuildWillingnessInterpretationAsync(ScenarioGuidanceRequest request, CancellationToken cancellationToken)
    {
        if (_statWillingnessProfileService is null || string.IsNullOrWhiteSpace(request.SelectedWillingnessProfileId))
        {
            return string.Empty;
        }

        var profile = await _statWillingnessProfileService.GetAsync(request.SelectedWillingnessProfileId, cancellationToken);
        if (profile is null || profile.Thresholds.Count == 0)
        {
            return string.Empty;
        }

        var targetStat = string.IsNullOrWhiteSpace(profile.TargetStatName)
            ? "Desire"
            : profile.TargetStatName.Trim();
        var statValue = ResolveAverageForStat(request, targetStat);
        var roundedDesire = (int)Math.Round(statValue, MidpointRounding.AwayFromZero);
        var threshold = profile.Thresholds
            .OrderBy(x => x.SortOrder)
            .ThenBy(x => x.MinValue)
            .FirstOrDefault(x => roundedDesire >= x.MinValue && roundedDesire <= x.MaxValue);

        if (threshold is null)
        {
            return string.Empty;
        }

        var examples = threshold.ExampleScenarios.Count == 0
            ? string.Empty
            : $" Examples: {string.Join(", ", threshold.ExampleScenarios)}.";

        return $"Willingness band '{threshold.ExplicitnessLevel}' ({threshold.MinValue}-{threshold.MaxValue}) from {targetStat}={roundedDesire}: {threshold.PromptGuideline}.{examples}";
    }

    private async Task<string> BuildResistanceInterpretationAsync(ScenarioGuidanceRequest request, CancellationToken cancellationToken)
    {
        if (_statResistanceProfileService is null)
        {
            return string.Empty;
        }

        var selectedId = request.SelectedResistanceProfileId;
        StatResistanceProfile? profile;
        if (string.IsNullOrWhiteSpace(selectedId))
        {
            profile = (await _statResistanceProfileService.ListAsync(cancellationToken))
                .FirstOrDefault(p => p.IsDefault);
        }
        else
        {
            profile = await _statResistanceProfileService.GetAsync(selectedId, cancellationToken);
        }

        if (profile is null || profile.Thresholds.Count == 0)
        {
            return string.Empty;
        }

        // Resolve target stat value
        var targetStat = string.IsNullOrWhiteSpace(profile.TargetStatName)
            ? "Loyalty"
            : profile.TargetStatName.Trim();

        var statValue = ResolveAverageForStat(request, targetStat);
        var roundedStat = (int)Math.Round(statValue, MidpointRounding.AwayFromZero);

        // T023: compute motivation score from behavioral dimensions
        var motivationScore = ComputeMotivationScore(request);
        var effectiveStat = Math.Min(roundedStat + motivationScore, 100);

        var threshold = profile.Thresholds
            .OrderBy(x => x.SortOrder)
            .ThenBy(x => x.MinValue)
            .FirstOrDefault(x => effectiveStat >= x.MinValue && effectiveStat <= x.MaxValue);

        if (threshold is null)
        {
            return string.Empty;
        }

        var examples = threshold.ExampleScenarios.Count == 0
            ? string.Empty
            : $" Examples: {string.Join(", ", threshold.ExampleScenarios)}.";

        return $"Resistance band '{threshold.ResistanceLevel}' ({threshold.MinValue}-{threshold.MaxValue}) from {targetStat}={roundedStat} (effective={effectiveStat}, motivation={motivationScore}): {threshold.Description}.{examples}";
    }

    private int ComputeMotivationScore(ScenarioGuidanceRequest request)
    {
        // Resolve per-character RuntimeEncounterStat values.
        // Default to 50 (neutral) when a character role or stat is not found.
        var stats = request.CharacterRuntimeStats;
        if (stats is null || stats.Count == 0)
        {
            return 0;
        }

        // Find characters by role
        var wifeStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "Wife", StringComparison.OrdinalIgnoreCase));
        var husbandStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "Husband", StringComparison.OrdinalIgnoreCase));
        var otherManStats = stats.Values.FirstOrDefault(s =>
            string.Equals(s.CharacterRole, "OtherMan", StringComparison.OrdinalIgnoreCase));

        // Resolve dimension values (default 50 = neutral)
        var attentiveness = husbandStats?.RuntimeEncounterStats?.TryGetValue("Attentiveness", out var att) == true
            ? att : 50;
        var intimacyAvailability = husbandStats?.RuntimeEncounterStats?.TryGetValue("IntimacyAvailability", out var ia) == true
            ? ia : 50;
        var selfRespect = wifeStats?.RuntimeEncounterStats?.TryGetValue("SelfRespect", out var sr) == true
            ? sr : 50;
        var persistencePastLimits = otherManStats?.RuntimeEncounterStats?.TryGetValue("PersistencePastLimits", out var ppl) == true
            ? ppl : 50;

        // Formula: ((100−Attentiveness) + (100−IntimacyAvailability) + (100−SelfRespect) + PersistencePastLimits) / 4
        var score = ((100 - attentiveness) + (100 - intimacyAvailability) + (100 - selfRespect) + persistencePastLimits) / 4.0;
        return (int)Math.Round(score, MidpointRounding.AwayFromZero);
    }

    private static double ResolveAverageForStat(ScenarioGuidanceRequest request, string statName)
    {
        if (string.Equals(statName, "Desire", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageDesire;
        }

        if (string.Equals(statName, "Restraint", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageRestraint;
        }

        if (string.Equals(statName, "Tension", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageTension;
        }

        if (string.Equals(statName, "Connection", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageConnection;
        }

        if (string.Equals(statName, "Dominance", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageDominance;
        }

        if (string.Equals(statName, "Loyalty", StringComparison.OrdinalIgnoreCase))
        {
            return request.AverageLoyalty;
        }

        return request.AverageDesire;
    }
}
